更新
SlimeTraditionalTranslation/RelicsOfCthonia pull request #5
Opened 2023-01-20 07:17 UTC by xwinhyukx

2023-01-20 09:53 UTC, xMikux requested changes

2023-01-20 09:53 UTC, xMikux commented on src/main/java/ne/fnfal113/relicsofcthonia/listeners/PiglinMainListener.java
> +                executeTradeMessage(event, "&c交易失敗! 豬布林對遺物狀態不滿意並在檢查時被銷毀!");
```suggestion
                executeTradeMessage(event, "&c交易失敗! 豬布林對遺物的狀態不滿意, 並在檢查時將其銷毀!");

```

2023-01-20 19:28 UTC, xMikux approved these changes

2023-01-21 14:16 UTC, weiii-joe approved these changes

2023-01-21 14:16 UTC, merged